### ISSUE TITLE
Регистрация всех членов команды в slack

### ISSUE THREAD

**Issue by jehy** [mami-drones/group4-encoder#1]

**Comment by ArtemiyM** [comment]
- [X] [Морозов Артемий Александрович](https://mami-drones.slack.com/messages/@artemiy_m/details/)
- [X] [Вятчин Глеб Константинович](https://mami-drones.slack.com/messages/@snickers.ror/details/)
- [x] [Степкина Александра Дмитриевна](https://mamidrones.slack.com/messages/@ganniballektor/details/)
- [x] [Ковалева Дарья Вячеславовна](https://mami-drones.slack.com/messages/@wolphwolph/details/)
- [x] [Синко Владислав Юрьевич](https://mami-drones.slack.com/messages/@goblin/details/)
- [X] [Ерёмин Иван Геннадьевич](https://mami-drones.slack.com/messages/@kermit/details/)
