### ISSUE TITLE
Регистрация всех членов команды в github

### ISSUE THREAD

**Issue by jehy** [mami-drones/group4-encoder#2]

**Comment by ArtemiyM** [comment]
- [X] [Морозов Артемий Александрович](mailto:morozov-artemiy@mail.ru) [vk](https://vk.com/archebald__png) [gh](https://github.com/ArtemiyM)
- [X] [Вятчин Глеб Константинович](mailto:snickers.ror@yandex.ru) [vk](https://vk.com/id98400838) [gh](https://github.com/snickersror)
- [x] [Степкина Александра Дмитриевна](mailto:ganniballektor@list.ru) [vk](https://vk.com/sffffgggg) [gh](https://github.com/ganniballektor)
- [x] [Ковалева Дарья Вячеславовна](mailto:alexa.kent17@gmail.com) [vk](https://vk.com/wolph2000) [gh](https://github.com/wolphwolph)
- [x] [Синко Владислав Юрьевич](mailto:sinko.vladis@yandex.ru) [vk](https://vk.com/id70012211) [gh](https://github.com/Goblin96) 
- [x] [Ерёмин Иван Геннадьевич](mailto:freston10@gmail.com) [vk](https://vk.com/id372431702) [gh](https://github.com/Festor)
